version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/postgres/initdb:/docker-entrypoint-initdb.d
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
